export const SITE = {
  website: "https://github.com/takei-shg/ST-portfolio",
  author: "Shigekazu Takei",
  profile: "https://github.com/takei-shg",
  desc: "Senior software engineer and cloud architect specializing in AWS-first, serverless platforms.",
  title: "Shigekazu Takei",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "Edit page",
    url: "https://github.com/takei-shg/ST-portfolio/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Asia/Tokyo",
} as const;
